export { default as LED } from './DeviceLED'
export { default as Toggle } from './ToggleSwitch'
export { default as FAN } from './DeviceFAN'
export { default as Slider} from './Slider'
export { default as Applications} from './Application'
